warmups = 10
duration = '10s'
max_concurrent_sessions = 4
parse_curl = true

[scenarios.facebook]
script = '''
curl https://www.facebook.com
'''

[scenarios.yahoo]
script = '''
curl https://www.yahoo.com
'''
